name: PC Card
description: 📺 PC Remote Card
type: lovelace
keywords:
  - pccard
  - remote
  - pc
  - htpc
author:
  name: catgirlkara
license: Apache License, Version 2.0
files:
  - pc-card.js
  - pc-card-editor.js
